SELECT TOP (1000) [id]
      ,[name]
      ,[state]
      ,[county]
      ,[district]
      ,[school]
      ,[regUserID]
      ,[wishlist_url]
      ,[about_me]
      ,[image_data]
  FROM [dbo].[teacher_list]